### ISSUE TITLE
Will this engine ever compete at TCEC or be merged into Leela?

### ISSUE THREAD

**Issue by gamer191** [dje-dev/Ceres#79]
Just curious

**Comment by dje-dev** [comment]
Ceres and LC0 have shared ideas and the best find their way into both engines. Currently most configurations LC0 engine tests as slightly stronger (circa 15 Elo) than Ceres at long time control.  They both have their strengths, for example Ceres excels with smaller networks (due to high engine speed) and Ceres has some interesting features to graph and chart out principal variations and compare games/tournaments graphically. But LC0 is more battle tested, runs on a much wider variety of hardware, and has some promising new enhancements (e.g. DAG).

Work on Ceres continues, but the focus is as a research platform rather than necessarily competing in TCEC. Current research work is focused on building out a training pipeline.
